name: HTML CSS Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Kiểm tra lỗi chính tả trong code
      - name: Lint HTML
        uses: Cyb3r-Jak3/htmlhint-action@v1
        with:
          files: '**/*.html'

      - name: Lint CSS
        run: |
          npm install -g stylelint stylelint-config-standard
          stylelint "**/*.css"
